name: Upload Website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS-Region: ${{ secrets.AWS_REGION }}
      
      - name: Build app
        run: npm install && npm run build
  
      - name: Deploy the site 
        run: aws s3 sync ./build s3://${{ secrets.AWS_S3_BUCKET}} --delete