name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: 
          - latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 
            - 18

      - name: Navigate to server directory
        run: cd ./server/server.js

      - name: Install dependencies
        id: install-dependencies
        run: npm install

      - name: Deploy to EC2
        uses: appleboy/ssh-action@main
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            git pull origin main
            npm install
            pm2 restart server.js
