name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Server Dependencies
        id: install-dependencies
        working-directory: ./server
        continue-on-error: false
        run: npm install

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOST: ${{ secrets.HOST_DNS }}
          USERNAME: ${{ secrets.USERNAME }}
        with:
          script: |
            date
            pwd
            ls -la
            cd ./server
            npm install
            git pull origin main
            npm install
            /usr/local/bin/pm2 restart server.js

      - name: Check PM2 process status
        run: /usr/local/bin/pm2 list
