name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.14.0

      - name: Install dependencies and deploy to EC2
        working-directory: ./server
        run: |
          npm install
          npm install -g pm2 
          git pull origin main
          pm2 restart server.js
        env:
          HOST: ${{ secrets.HOST_DNS }}
          USERNAME: ${{ secrets.USERNAME }}
          KEY: ${{ secrets.EC2_SSH_KEY }}
