name: Deploy to EC2

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  docker-username: ${{ secrets.DOCKER_USERNAME }}
  docker-token: ${{ secrets.DOCKER_TOKEN }}
  key: ${{ secrets.EC2_SSH_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{  secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: true
          dockerfile: ./Dockerfile
          tags: abubakarmeigag/beko-videos:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{  secrets.DOCKER_TOKEN }}

      - name: Set permissions for private key
        run: |
          echo "${{ env.key }}" > key.pem
          chmod 600 key.pem
          
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          secret: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          port: 22
          script: |
            sudo docker pull abubakarmeigag/beko-videos:latest
            sudo docker stop beko-videos || true
            sudo docker rm beko-videos || true
            sudo docker run -d --name beko-image -p 5002:5002 -e DBConnLink=${{ secrets.DB_LINK }} abubakarmeigag/beko-videos:latest


          

      # - name: Pull Docker image
      #   run: |
      #     ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@ec2-54-224-245-13.compute-1.amazonaws.com 'sudo docker pull abubakarmeigag/beko-videos:latest'

      # - name: Stop running container
      #   run: |
      #     ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@ec2-54-224-245-13.compute-1.amazonaws.com 'sudo docker stop beko-videos || true'
      #     ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@ec2-54-224-245-13.compute-1.amazonaws.com 'sudo docker rm beko-videos || true'

      # - name: Run new container
      #   run: |
      #     ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@ec2-54-224-245-13.compute-1.amazonaws.com 'sudo docker run -d --name beko-image -p 5002:5002 -e DB_LINK=${{ secrets.DB_LINK }} abubakarmeigag/beko-videos:latest'

    # steps:
    #   - name: Checkout code
    #     uses: actions/checkout@v2

    #   - name: Setup Node.js
    #     uses: actions/setup-node@v4
    #     with:
    #       node-version: 18.14.0

    #   - name: Install ssh client
    #     run: sudo apt-get install openssh-client -y

    #   - name: executing remote ssh commands using password
    #     uses: appleboy/ssh-action@v1.0.3
    #     with:
    #       host: ${{ secrets.HOST_DNS }}
    #       username: ${{ secrets.USERNAME }}
    #       key: ${{ secrets.EC2_SSH_KEY }}
    #       port: 22
    #       script: |
    #         cd  AWS-Beko-videos-pro/server
    #         npm install
    #         git pull origin main
    #         pm2 restart 0
