name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Server Dependencies
        id: install-dependencies
        working-directory: ./server
        continue-on-error: false
        run: npm install

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}

      - name: Run Tests
        run: echo "No tests are available for this project"

      - name: Start Server/Run Application
        id: start-server
        run: |
          npm install -g pm2
          pm2 restart BackendAPI
        working-directory: ./server
        continue-on-error: false

      - name: Handle Errors
        if: steps.install-dependencies.outcome != 'success' || steps.create-env-file.outcome != 'success' || steps.start-server.outcome != 'success'
        run: echo "::set-output name=workflow-error::true"
