name: Update EC2 server

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: 
          - latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Server Dependencies
        id: install-dependencies
        run: npm ci

      - name: Deploy to Server 1
        uses: beko-ec2-server/ssh-deploy@main

      - name: Create .env File
        id: create-env-file
        run: |
          touch ./server/.env
          echo "EC2_HOST=${{ secrets.HOST_DNS }}" >> ./server/.env
          echo "EC2_SSH_KEY=${{ secrets.EC2_SSH_KEY }}" >> ./server/.env
          echo "EC2_USERNAME=${{ secrets.EC2_USERNAME }}" >> ./server/.env

      - name: Start Server/Run Application
        working-directory: ./server
        continue-on-error: false
        id: start-server
        run: pm2 start server.js
