name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Server Dependencies
        id: install-dependencies
        working-directory: ./server
        continue-on-error: false
        run: npm install

      - name: Create .env File
        id: create-env-file
        run: |
          touch ./server/.env
          echo "EC2_HOST=${{ secrets.HOST_DNS }}" >> ./server/.env
          echo "EC2_SSH_KEY=${{ secrets.EC2_SSH_KEY }}" >> ./server/.env
          echo "EC2_USERNAME=${{ secrets.USERNAME }}" >> ./server/.env
        working-directory: ./server
        continue-on-error: false

      - name: Run Tests
        run: echo "No tests are available for this project"

      - name: Start Server/Run Application
        id: start-server
        run: |
          npm install -g pm2
          pm2 restart BackendAPI
        working-directory: ./server
        continue-on-error: false

      - name: Handle Errors
        if: steps.install-dependencies.outcome != 'success' || steps.create-env-file.outcome != 'success' || steps.start-server.outcome != 'success'
        run: echo "::set-output name=workflow-error::true"
