name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies and pm2
        run: |
          npm install -g pm2

      - name: Install dependencies and deploy to EC2
        working-directory: ./server
        run: |
          pwd
          ls -la
          npm install
          git pull origin main
          npm install
          pm2 start server.js

      - name: Check PM2 process status
        working-directory: ./server
        run: pm2 list
        env:
          HOST: ${{ secrets.HOST_DNS }}
          USERNAME: ${{ secrets.USERNAME }}
          KEY: ${{ secrets.EC2_SSH_KEY }}
