name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Server Dependencies
        id: install-dependencies
        working-directory: ./server
        continue-on-error: false
        run: npm install

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        env:
          ec2-ssh-key: ${{ secrets.EC2_SSH_KEY }}
          host-dns: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}

      - name: Run Tests
        run: echo "No tests are available for this project"

      - name: Install dependencies and deploy to EC2
        working-directory: ./server
        run: |
          date
          pwd
          ls -la
          npm install
          git pull origin main
          npm install
          /usr/local/bin/pm2 start server.js

      - name: Restart PM2 process
        working-directory: ./server
        run: /usr/local/bin/pm2 restart server.js

      - name: Check PM2 process status
        working-directory: ./server
        run: /usr/local/bin/pm2 list

      - name: Check PM2 logs
        working-directory: ./server
        run: /usr/local/bin/pm2 logs

      - name: Debugging Info
        working-directory: ./server
        run: |
          date
          pwd
          ls -la

      - name: Handle Errors
        if: steps.install-dependencies.outcome != 'success'
        run: echo "::set-output name=workflow-error::true"
